### ISSUE TITLE
Package UUID in output does not match PACKAGE ID field in Admin Console

### ISSUE THREAD

**Issue by dominicwatkins** [adobe/adobe-license-decoder.rs#14]
**Describe the bug**
Creating a license package on the Adobe Admin Console and deploying it, then running the Adobe License Decoder, it was noted that the ID did not match in the output with that shown for the package on the Admin Console

**To Reproduce**
1. Create a package on the Adobe Admin Console which is licensed via FRL
2. Deploy the package or apply the license (in the case of a license-only package) using the licensing toolkit: adobe-licensing-toolkit.exe -p -i -f ngl-preconditioning-data.json
3. download the latest Adobe License Decoder and execute it with the maximum verbosity option: adobe-license-decoder.windows_x86_64.exe -vv
4. Observe the line in the output described as "Package UUID" and compare with the field in the package details on the Admin Console named "PACKAGE ID".

**Security note**: do *not* attach license files.

**Observed behavior**
The ID in the Adobe License Decoder output does not match that of the corresponding package shown in the Admin Console, although both values appear to be the same format of 8, 4, 4, 4 and 12 alphanumerics separated by dashes in both instances.

**Expected behavior**
The IDs should match to allow an installed license to be matched to an Admin Console package and/or org ID.

**Operating System**
- Tested on Windows
- OS version Windows 10 20H2

**Additional context**

**Comment by adobeDan** [comment]
So this turns out to be both a bug and an enhancement request and a documentation request :).

1. Since the Package UUID displayed in verbose mode is expected to match the Admin Console's Package ID and doesn't, that's a bug and we shouldn't show it until it does.
2. Since we can't actually get the package ID as shown in the Admin Console without a new back-end API to fetch it from the admin console, that's an enhancement request which will have to wait until the back-end API is implemented.
3. Since we show a package UUID that doesn't meet customer expectation, we should document this.

I will leave this issue open until all three aspects are solved, and I will change labels to remove "bug" and "documentation" as I update those.

**Comment by adobeDan** [comment]
OK, so we have a resolution:

1. The admin console now includes a "Package License ID" in the details shown about each package.  This "Package License ID" field is what the `adobe-license-decoder` and the `adobe-licensing-toolkit` call the `npdId` of the package.  That means this new "Package License ID" field can be used to match up packages on client machines and those in the Admin Console listing.
2. With this new feature, there is no reason to display the decoded `npdId` in the `adobe-license-decoder`.  So we will remove it as a way of fixing this bug.
3. We need to document that the `npdId` and the "Package License ID" are the same thing.  Because people don't read documentation, I'm inclined to just replace the current "Package UUID" line output by the decoder with a "Package License ID" line that shows the  npdId, even though it's the same as the `npdId` shown on the line above.  @dominicwatkins, do you agree?

Once these changes are released, we can close this issue.
